insert into Attraction (Name, Address, DistrictNr) values ('Carousel', 'Prater Hauptallee', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Haunted House', 'Schönbrunner Schloßstraße', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Ferris Wheel', 'Riesenradplatz', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Roller Coaster', 'Prater', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Water Slide', 'Böhmischer Prater', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Museum of Technology', 'Mariahilfer Straße 212', 15);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Zoo', 'Maxingstraße 13b', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Botanical Garden', 'Rennweg 14', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Belvedere Palace', 'Prinz Eugen-Straße 27', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Art History Museum', 'Maria-Theresien-Platz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Natural History Museum', 'Burgring 7', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Leopold Museum', 'Museumsplatz 1', 7);
insert into Attraction (Name, Address, DistrictNr) values ('Albertina Museum', 'Albertinaplatz 1', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Schönbrunn Palace', 'Schönbrunner Schloßstraße 47', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna State Opera', 'Opernring 2', 1);
insert into Attraction (Name, Address, DistrictNr) values ('St. Stephen\'s Cathedral', 'Stephansplatz 3', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Hundertwasser House', 'Kegelgasse 34-38', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Danube Tower', 'Donauturmstraße 4', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Naschmarkt', 'Naschmarkt', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Hofburg Palace', 'Hofburg', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna City Hall', 'Friedrich-Schmidt-Platz 1', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Austrian Parliament Building', 'Dr.-Karl-Renner-Ring 3', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Rathausplatz', 'Rathausplatz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Woods', 'Wienerwald', 14);
insert into Attraction (Name, Address, DistrictNr) values ('Donauinsel', 'Donauinsel', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Kahlenberg', 'Kahlenberg', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Liesing River Walk', 'Promenadeweg Liesing', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Volksgarten', 'Volksgarten', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Karlsplatz', 'Karlsplatz', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Military History Museum', 'Arsenal Objekt 1', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Otto Wagner Villa', 'Hüttelbergstraße 26', 14);
insert into Attraction (Name, Address, DistrictNr) values ('Zentralfriedhof', 'Simmeringer Hauptstraße 234', 11);
insert into Attraction (Name, Address, DistrictNr) values ('Neptune Fountain at Schönbrunn', 'Schönbrunner Schloßstraße 47', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Mariahilfer Straße Shopping Street', 'Mariahilfer Straße', 6);
insert into Attraction (Name, Address, DistrictNr) values ('MuseumsQuartier', 'Museumsplatz 1', 7);
insert into Attraction (Name, Address, DistrictNr) values ('Lainzer Tiergarten', 'Lainzer Tor', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Kurpark Oberlaa', 'Kurbadstraße 10', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Augarten', 'Obere Augartenstraße 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Prater Museum', 'Oswald-Thomas-Platz 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('House of the Sea', 'Fritz-Grünbaum-Platz 1', 6);
insert into Attraction (Name, Address, DistrictNr) values ('Seegrotte Hinterbrühl', 'Grutschgasse 2a', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Thermalbad Vösendorf', 'Seepark Vösendorf', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Burg Liechtenstein', 'Am Hausberg 2', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Observatory', 'Türkenschanzstraße 17', 18);
insert into Attraction (Name, Address, DistrictNr) values ('Johann Strauss Monument', 'Stadtpark', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Heeresgeschichtliches Museum', 'Arsenal Objekt 1', 3);
insert into Attraction (Name, Address, DistrictNr) values ('MUMOK (Museum of Modern Art)', 'Museumsplatz 1', 7);
insert into Attraction (Name, Address, DistrictNr) values ('House of Music', 'Seilerstätte 30', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Beethoven Pasqualatihaus', 'Mölker Bastei 8', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Technical Museum Vienna', 'Mariahilfer Straße 212', 15);
insert into Attraction (Name, Address, DistrictNr) values ('The Third Man Museum', 'Pressgasse 25', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Ernst Fuchs Museum', 'Hüttelbergstraße 26', 14);
insert into Attraction (Name, Address, DistrictNr) values ('Schmetterlinghaus (Butterfly House)', 'Burggarten', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Crime Museum', 'Große Sperlgasse 24', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Chocolate Museum Vienna', 'Willendorfer Gasse 2-8', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Gasometer City', 'Guglgasse 6', 11);
insert into Attraction (Name, Address, DistrictNr) values ('Bank Austria Kunstforum', 'Freyung 8', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Liesing River Path', 'Liesingbachweg', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Liesing Business Park', 'Liesinger-Platz 1', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Ottakring Brewery', 'Ottakringer Platz 1', 16);
insert into Attraction (Name, Address, DistrictNr) values ('Donaupark', 'Arbeiterstrandbadstraße', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Perchtoldsdorf Castle', 'Marktplatz 11', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Sigmund Freud Museum', 'Berggasse 19', 9);
insert into Attraction (Name, Address, DistrictNr) values ('Schoenbrunn Orangery', 'Schönbrunner Schloßstraße', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Karl Marx-Hof', 'Heiligenstädter Straße 82', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna City Beach Club', 'Neue Donau Mitte', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Woods', 'Wienerwald', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Neue Donau', 'Neue Donau', 21);
insert into Attraction (Name, Address, DistrictNr) values ('Alte Donau', 'Arbeiterstrandbadstraße', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Kahlenberg', 'Josefsdorf 38', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Cobenzl', 'Am Cobenzl 94', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Burg Kreuzenstein', 'Kreuzensteiner Straße', 21);
insert into Attraction (Name, Address, DistrictNr) values ('Lainzer Tiergarten', 'Hermesvilla', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Volksgarten', 'Dr.-Karl-Renner-Ring', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Stadtpark', 'Parkring 1', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Prater', 'Prater', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Karlskirche', 'Kreuzherrengasse 1', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Augarten Contemporary', 'Obere Augartenstraße 1e', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Gloriette Schönbrunn', 'Schönbrunner Schloßstraße 47', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Danube Tower', 'Donauturmstraße 4', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Belvedere 21', 'Arsenalstraße 1', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Museum of Illusions', 'Wallnerstraße 4', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Donau Zentrum', 'Wagramer Straße 94', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Flakturm Museum', 'Esterházypark', 6);
insert into Attraction (Name, Address, DistrictNr) values ('Wiener Riesenrad', 'Riesenradplatz 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Porcelain Manufactory Augarten', 'Obere Augartenstraße 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Klimt Villa', 'Feldmühlgasse 11', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Geymüllerschlössel', 'Pötzleinsdorfer Straße 102', 18);
insert into Attraction (Name, Address, DistrictNr) values ('Hermesvilla', 'Lainzer Tiergarten', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Imperial Carriage Museum', 'Schönbrunner Schloßstraße 47', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Wien Museum MUSA', 'Felderstraße 6-8', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Wien Museum Karlsplatz', 'Karlsplatz 8', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Funeral Museum at Vienna\'s Central Cemetery', 'Simmeringer Hauptstraße 234', 11);
insert into Attraction (Name, Address, DistrictNr) values ('Time Travel Vienna', 'Habsburgergasse 10a', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Mozarthaus Vienna', 'Domgasse 5', 1);
insert into Attraction (Name, Address, DistrictNr) values ('21er Haus', 'Quartier Belvedere', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Schwarzenbergplatz', 'Schwarzenbergplatz', 3);
insert into Attraction (Name, Address, DistrictNr) values ('The Third Man Tour', 'Various Locations', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Pötzleinsdorfer Schlosspark', 'Geymüllergasse', 18);
insert into Attraction (Name, Address, DistrictNr) values ('Zoo Vienna', 'Maxingstraße 13b', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Liechtenstein Park', 'Fürstengasse 1', 9);
insert into Attraction (Name, Address, DistrictNr) values ('Palmenhaus Schönbrunn', 'Schönbrunner Schloßstraße', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Stadion Center', 'Olympiaplatz 2', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Madame Tussauds Vienna', 'Riesenradplatz 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Kurpark Oberlaa', 'Kurbadstraße 10', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Gloriette Cafe', 'Schönbrunner Schloßstraße 47', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Museum of Applied Arts (MAK)', 'Stubenring 5', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Otto Wagner Pavillon', 'Karlsplatz', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Naturhistorisches Museum Wien', 'Burgring 7', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Volksoper Vienna', 'Währinger Straße 78', 9);
insert into Attraction (Name, Address, DistrictNr) values ('Viktor Frankl Museum', 'Mariannengasse 1', 9);
insert into Attraction (Name, Address, DistrictNr) values ('Kunsthalle Wien', 'Museumsplatz 1', 7);
insert into Attraction (Name, Address, DistrictNr) values ('Secession Building', 'Friedrichstraße 12', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Theater in der Josefstadt', 'Josefstädter Straße 26', 8);
insert into Attraction (Name, Address, DistrictNr) values ('Liesing Skate Park', 'Perchtoldsdorfer Straße 10', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Schönbrunn Zoo', 'Maxingstraße 13b', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Prater Museum', 'Oswald-Thomas-Platz 1', 2);
insert into Attraction (Name, Address, DistrictNr) values ('Danube Island', 'Donauinsel', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Heiligenstadt Park', 'Armbrustergasse 15', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Liesinger Bad', 'Karl-Tornay-Gasse 44', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Türkenschanzpark', 'Peter-Jordan-Straße 76', 18);
insert into Attraction (Name, Address, DistrictNr) values ('Amalienbad', 'Reumannplatz 23', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Schubert's Birthplace', 'Nußdorfer Straße 54', 9);
insert into Attraction (Name, Address, DistrictNr) values ('Beethoven Museum', 'Probusgasse 6', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Karl-Marx-Hof', 'Heiligenstädter Straße 82', 19);
insert into Attraction (Name, Address, DistrictNr) values ('Sisi Museum', 'Hofburg, Michaelerkuppel', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Jewish Museum Vienna', 'Dorotheergasse 11', 1);
insert into Attraction (Name, Address, DistrictNr) values ('District Museum Simmering', 'Enkplatz 2', 11);
insert into Attraction (Name, Address, DistrictNr) values ('District Museum Floridsdorf', 'Prager Straße 33', 21);
insert into Attraction (Name, Address, DistrictNr) values ('District Museum Donaustadt', 'Kagraner Platz 53/54', 22);
insert into Attraction (Name, Address, DistrictNr) values ('District Museum Liesing', 'Canavesegasse 24', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Wotruba Church', 'Ottillingerplatz 1', 23);
insert into Attraction (Name, Address, DistrictNr) values ('Lainzer Wildlife Park', 'Hermesstraße', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna University Botanical Garden', 'Rennweg 14', 3);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Woods', 'Mauerbachstraße 174', 14);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Central Cemetery', 'Simmeringer Hauptstraße 234', 11);
insert into Attraction (Name, Address, DistrictNr) values ('Friedhof der Namenlosen', 'Alberner Hafen', 11);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna River Bike Path', 'Along Wien River', 5);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Ring Tram', 'Schwedenplatz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna City Marathon Route', 'Starts at Wagramer Straße', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Therme Wien Spa', 'Kurbadstraße 14', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Freyung', 'Freyung', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna State Ballet', 'Opernring 2', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Stephansdom North Tower', 'Stephansplatz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Philharmonic', 'Bösendorferstraße 12', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna International Centre', 'Wagramer Straße 5', 22);
insert into Attraction (Name, Address, DistrictNr) values ('United Nations Office at Vienna', 'Wagramer Straße 5', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Donauturm', 'Donauturmstraße 4', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Danube Park', 'Arbeiterstrandbadstraße', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Danube Island Festival Grounds', 'Donauinsel', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Lobau National Park', 'Lobgrundstraße', 22);
insert into Attraction (Name, Address, DistrictNr) values ('Kunsthistorisches Museum', 'Maria-Theresien-Platz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Naturhistorisches Museum', 'Maria-Theresien-Platz', 1);
insert into Attraction (Name, Address, DistrictNr) values ('Albertina Modern', 'Karlsplatz 5', 4);
insert into Attraction (Name, Address, DistrictNr) values ('Theater an der Wien', 'Linke Wienzeile 6', 6);
insert into Attraction (Name, Address, DistrictNr) values ('Haus des Meeres', 'Fritz-Grünbaum-Platz 1', 6);
insert into Attraction (Name, Address, DistrictNr) values ('Schönbrunn Zoo', 'Maxingstraße 13b', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Palmenhaus Schönbrunn', 'Schönbrunner Schloßstraße', 13);
insert into Attraction (Name, Address, DistrictNr) values ('Technical Museum', 'Mariahilfer Straße 212', 15);
insert into Attraction (Name, Address, DistrictNr) values ('Amalienbad', 'Reumannplatz 23', 10);
insert into Attraction (Name, Address, DistrictNr) values ('Vienna Woods', 'Wienerwald 2', 23);
