insert into Event (Name, Date, Address, Type, DistrictNr) values ('Kunsthistorisches Museum Visit', '2023-06-01', 'Maria-Theresien-Platz', 'museum visit', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Open Air Jazz Concert', '2023-07-15', 'Donauinsel', 'music festival', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Schönbrunn Palace Outdoor Cinema', '2023-08-05', 'Schönbrunner Schloßstraße', 'movie screening', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Belvedere Art Exhibition', '2023-09-10', 'Prinz Eugen-Straße', 'art exhibition', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Philharmonic Park Concert', '2023-06-20', 'Musikvereinsplatz', 'classical concert', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Street Art Tour', '2023-07-25', 'Breite Gasse', 'art tour', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Naschmarkt Food Festival', '2023-08-12', 'Naschmarkt', 'food festival', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna State Opera Open Day', '2023-09-01', 'Opernring', 'open day', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('MuseumsQuartier Summer Lounge', '2023-07-03', 'Museumsplatz', 'cultural gathering', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Outdoor Film Festival at Rathausplatz', '2023-08-22', 'Rathausplatz', 'film festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Historic Tram Ride Event', '2023-09-18', 'Ringstraße', 'cultural event', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Literature Festival', '2023-06-30', 'Heldenplatz', 'literature festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Danube Island Kite Festival', '2023-07-12', 'Donauinsel', 'outdoor activity', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Volksgarten Classical Music Night', '2023-08-18', 'Volksgarten', 'classical music', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Mariahilfer Street Art Show', '2023-09-22', 'Mariahilfer Straße', 'art show', 6);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Jazz Floor Festival', '2023-06-28', 'Spittelberggasse', 'jazz festival', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopold Museum Private Viewing', '2023-07-08', 'Museumsplatz', 'private museum tour', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Grinzing Wine Tasting', '2023-08-01', 'Grinzinger Straße', 'wine tasting', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Classical Recital', '2023-09-05', 'Währinger Straße', 'classical concert', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hundertwasserhaus Tour', '2023-06-12', 'Kegelgasse', 'guided tour', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Karlsplatz Art Fair', '2023-07-14', 'Karlsplatz', 'art fair', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donaukanal Street Party', '2023-08-08', 'Donaukanal', 'street festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Prater Festival of Lights', '2023-09-15', 'Prater', 'light festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('St. Stephen\'s Cathedral Choir Performance', '2023-06-20', 'Stephansplatz', 'choir concert', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Viennese Coffee House Culture Day', '2023-07-25', 'Freihausviertel', 'cultural celebration', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Augarten Porcelain Workshop', '2023-08-20', 'Obere Augartenstraße', 'craft workshop', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Bio Center Science Day', '2023-09-03', 'Dr.-Bohr-Gasse', 'science festival', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ringstrasse Architectural Tour', '2023-06-25', 'Ringstraße', 'guided walk', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Woods Hiking Day', '2023-07-18', 'Vienna Woods', 'hiking event', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Kahlenberg Sunset Concert', '2023-08-27', 'Kahlenberg', 'outdoor concert', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Zentralfriedhof Guided History Tour', '2023-09-09', 'Simmeringer Hauptstraße', 'historical tour', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Fashion Week Vienna', '2023-06-15', 'MuseumsQuartier', 'fashion event', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Outdoor Shakespeare Festival', '2023-07-29', 'Burggarten', 'theatre festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna International Film Festival', '2023-08-18', 'Gartenbaukino', 'film festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ferris Wheel Dinner Event', '2023-09-21', 'Prater', 'dining event', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Symphony Open Air', '2023-10-05', 'Schönbrunn Palace', 'classical music', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Albertina Modern Gallery Night', '2023-10-15', 'Karlsplatz 5', 'art exhibition', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Döbling Harvest Festival', '2023-10-22', 'Heiligenstädter Park', 'cultural festival', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Otto Wagner Villa Tour', '2023-11-01', 'Hüttelbergstraße', 'architecture tour', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Art Week', '2023-11-20', 'Various Locations', 'art week', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau Design Market', '2023-12-05', 'Neubaugasse', 'design market', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Wine and Jazz Evening', '2023-10-30', 'Landstraßer Hauptstraße', 'wine and jazz', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Chamber Orchestra Concert', '2023-11-10', 'Kalvarienberggasse', 'chamber music', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Street Art and Food Tour', '2023-11-25', 'Quellenstraße', 'art and food tour', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Film and History Night', '2023-12-15', 'Margaretenplatz', 'film night', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Christmas Market at Rathausplatz', '2023-12-01', 'Rathausplatz', 'christmas market', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Medieval Festival at Heldenplatz', '2023-10-08', 'Heldenplatz', 'medieval festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Jazz Night', '2023-11-05', 'Am Spitz', 'jazz night', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Classical Music Morning', '2023-10-21', 'Linzer Straße', 'classical music', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Local Theater Performance', '2023-11-12', 'Simmeringer Hauptstraße', 'theater', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wieden Poetry Slam', '2023-12-10', 'Karlsplatz', 'poetry slam', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Festival of Lights', '2023-10-28', 'Handelskai', 'light festival', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Autumn Arts Festival', '2023-11-15', 'Meidlinger Hauptstraße', 'arts festival', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Kunst Haus Wien Green Day', '2023-12-05', 'Untere Weißgerberstraße', 'environmental event', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Historical Reenactment', '2023-11-30', 'Prater Hauptallee', 'historical reenactment', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Opernring New Year’s Eve Concert', '2023-12-31', 'Opernring', 'new year concert', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Antique Book Fair', '2023-10-12', 'Josefstädter Straße', 'book fair', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Student Film Festival', '2023-11-19', 'Währinger Straße', 'film festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Spring Festival', '2023-10-14', 'Maxingstraße', 'spring festival', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim-Fünfhaus Art and Craft Fair', '2023-12-20', 'Reindorfgasse', 'craft fair', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Millennium Art Exhibition', '2000-09-15', 'MuseumsQuartier', 'art exhibition', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wien River Music Festival', '2002-08-05', 'Wienflussweg', 'music festival', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna History Walk', '2004-06-12', 'Michaelerplatz', 'guided walk', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donaustadt Nature Walk', '2006-04-22', 'Lobau', 'nature walk', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Belvedere Spring Festival', '2008-05-09', 'Prinz Eugen-Straße', 'cultural festival', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Kahlenberg Jazz Nights', '2010-07-17', 'Kahlenberg', 'jazz night', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Viennese Ballroom Dancing', '2012-12-31', 'Hofburg Palace', 'ballroom dancing', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Summer Screenings in the Park', '2014-08-15', 'Volksgarten', 'film screening', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neue Donau Water Festival', '2016-09-03', 'Neue Donau', 'water sports', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Poetry Reading', '2018-11-25', 'Hernalser Hauptstraße', 'literature festival', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Design Week', '2020-10-01', 'Freyung', 'design week', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Museum of Natural History Night Tour', '2021-07-15', 'Burgring 7', 'night tour', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Craft Beer Festival', '2022-06-10', 'Ottakringer Platz', 'beer festival', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Autumn Art Tour', '2023-09-21', 'Rennweg', 'art tour', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Christmas in Vienna', '2024-12-24', 'Stephansplatz', 'christmas celebration', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Marathon', '2001-05-06', 'Ringstraße', 'sports event', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Schubert Music Festival', '2003-11-19', 'Schubert Park', 'music festival', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Literature Fair', '2005-03-15', 'Mariahilfer Straße', 'literature fair', 6);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Outdoor Sculpture Exhibition', '2007-07-23', 'Karlsplatz', 'art exhibition', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Theater Festival', '2009-09-10', 'Prater Hauptallee', 'theater festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Culinary Nights', '2011-08-30', 'Margaretenplatz', 'food festival', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Light Festival', '2013-12-15', 'Donaukanal', 'light festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Art Night', '2015-10-25', 'Währinger Straße', 'art night', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Film Festival on Rathausplatz', '2017-08-20', 'Rathausplatz', 'film festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Spring Concert', '2019-05-15', 'Simmeringer Hauptstraße', 'concert', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Writers Festival', '2000-04-20', 'Burggasse', 'literature festival', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Währing Autumn Jazz Session', '2001-09-11', 'Gersthofer Straße', 'jazz festival', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donauinsel Pop Concert', '2002-07-05', 'Donauinsel', 'pop concert', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Gourmet Festival Wien', '2003-05-25', 'Naschmarkt', 'gourmet festival', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Film Noir Festival', '2004-10-12', 'Burg Kino', 'film festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Spring Flower Show', '2005-03-18', 'Am Spitz', 'flower show', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim-Fünfhaus Cultural Parade', '2006-06-30', 'Reindorfgasse', 'cultural parade', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Art and Craft Market', '2007-12-07', 'Thaliastraße', 'craft market', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Modern Dance Festival', '2008-11-15', 'MuseumsQuartier', 'dance festival', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donaustadt Dragon Boat Race', '2009-08-22', 'Alte Donau', 'boat race', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Classical Music Days', '2010-05-09', 'Hernalser Hauptstraße', 'classical music', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Literary Readings', '2011-04-14', 'Landstraßer Hauptstraße', 'literary reading', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Summer Festival', '2012-07-17', 'Simmeringer Platz', 'summer festival', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Winter Markets', '2013-12-05', 'Hütteldorfer Straße', 'winter market', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Fashion Week', '2014-09-25', 'Margaretenstraße', 'fashion week', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Circus Festival', '2015-06-12', 'Prater', 'circus festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Historical Reenactment', '2016-08-03', 'Schönbrunn Palace', 'historical event', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Community Art Project', '2017-10-10', 'Meidlinger Markt', 'community art', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Jazz Night', '2018-03-20', 'Josefstädter Straße', 'jazz night', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Science Expo', '2019-02-15', 'Währinger Straße', 'science expo', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau International Art Festival', '2020-11-28', 'Neubaugasse', 'international art', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wieden Summer Opera', '2021-07-21', 'Karlsplatz', 'opera event', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Outdoor Gallery', '2022-04-15', 'Hietzinger Hauptstraße', 'outdoor gallery', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Techno Parade', '2023-05-30', 'Quellenstraße', 'techno parade', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Light Sculpture Exhibition', '2024-01-25', 'Brigittenauer Lände', 'light exhibition', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Book Fair', '2000-10-21', 'Mariahilfer Straße', 'book fair', 6);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Prater Spring Carnival', '2001-03-15', 'Prater', 'carnival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Jazz Festival', '2002-05-10', 'Alser Straße', 'jazz festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Art Walk', '2003-04-20', 'Prater Hauptallee', 'art walk', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Classical Music Marathon', '2004-11-11', 'Musikverein', 'classical music', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Harvest Festival', '2005-09-25', 'Hietzinger Hauptstraße', 'harvest festival', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Autumn Art Fair', '2006-10-08', 'Linzer Straße', 'art fair', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Döbling Wine and Art Festival', '2007-08-19', 'Grinzinger Straße', 'wine and art', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Währing Classical Music Days', '2008-06-06', 'Gersthofer Straße', 'classical music', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donauinsel Film Festival', '2009-07-14', 'Donauinsel', 'film festival', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Fashion Show', '2010-02-27', 'Margaretenplatz', 'fashion show', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Spring Parade', '2011-04-23', 'Quellenstraße', 'parade', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau Photography Exhibition', '2012-03-08', 'Neubaugasse', 'photography exhibition', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Summer Dance', '2013-07-19', 'Thaliastraße', 'dance event', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Cultural Festival', '2014-05-15', 'Meidlinger Hauptstraße', 'cultural festival', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering History Days', '2015-09-10', 'Simmeringer Hauptstraße', 'history event', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Art and Jazz Night', '2016-08-21', 'Landstraßer Hauptstraße', 'art and jazz', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Literary Salon', '2017-01-12', 'Hernalser Hauptstraße', 'literary salon', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim-Fünfhaus Music Festival', '2018-12-05', 'Reindorfgasse', 'music festival', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Community Art Days', '2019-10-20', 'Am Spitz', 'community art', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Autumn Music Series', '2020-11-07', 'Josefstädter Straße', 'music series', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wieden Artisan Market', '2021-06-15', 'Karlsplatz', 'artisan market', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Lantern Festival', '2022-02-11', 'Brigittenauer Lände', 'lantern festival', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna International Arts Festival', '2023-07-20', 'Various Locations', 'arts festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt New Year's Eve Party', '2024-12-31', 'Prater', 'new year's eve', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Opera Ball', '2000-02-14', 'Wiener Staatsoper', 'ball', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donauinsel Rock Festival', '2001-07-08', 'Donauinsel', 'music festival', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wieden Winter Theatre Festival', '2002-12-11', 'Theater an der Wien', 'theatre festival', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Autumn Jazz Nights', '2003-09-20', 'Theater in der Josefstadt', 'jazz night', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Biennale for Art and Technology', '2004-06-18', 'MuseumsQuartier', 'art and tech', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Street Food Market', '2005-05-03', 'Prater Hauptallee', 'food market', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Döbling Garden Festival', '2006-04-14', 'Türkenschanzpark', 'garden festival', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Architecture Day', '2007-10-05', 'Belvedere Palace', 'architecture day', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Cultural Heritage Day', '2008-09-15', 'Ottakringer Brauerei', 'heritage day', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Global Film Festival', '2009-11-10', 'Votiv Kino', 'film festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Harvest Day', '2010-10-12', 'Pezzlpark', 'harvest day', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau Culture and Art Days', '2011-08-22', 'Spittelberg', 'culture and art', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Historical Fair', '2012-06-07', 'Simmeringer Hauptstraße', 'historical fair', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Spring Art Exhibition', '2013-03-28', 'Meidlinger Markt', 'art exhibition', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Film Appreciation Night', '2014-07-15', 'Technisches Museum', 'film night', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Literary Weekend', '2015-04-10', 'Margaretenplatz', 'literature event', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Summer Arts Festival', '2016-08-21', 'Hauptbahnhof', 'arts festival', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Water Sports Day', '2017-07-19', 'Alte Donau', 'water sports', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Währing Garden Show', '2018-05-09', 'Türkenschanzpark', 'garden show', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Science Festival', '2019-09-27', 'Old AKH', 'science festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Night Run', '2020-10-06', 'Ringstraße', 'night run', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Music and Arts Festival', '2021-06-18', 'Schönbrunn Palace', 'music and arts', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim Craft Beer and Music Night', '2022-04-12', 'Reindorfgasse', 'craft beer night', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Digital Art Show', '2023-02-15', 'Millennium Tower', 'digital art', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Film Premiere Gala', '2024-09-05', 'Karmelitermarkt', 'film premiere', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Film Festival', '2000-06-20', 'Gartenbaukino', 'film festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Jazz Festival', '2001-07-15', 'Jazzland', 'jazz festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Schönbrunn Summer Night Concert', '2002-08-30', 'Schönbrunn Palace', 'classical music', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donauinsel Sports Day', '2003-05-25', 'Donauinsel', 'sports event', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Belvedere Art Show', '2004-10-12', 'Belvedere Palace', 'art exhibition', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Literature Festival', '2005-04-15', 'Burgtheater', 'literature festival', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Spring Market', '2006-03-22', 'Hietzinger Hauptstraße', 'market', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Döbling Family Picnic Day', '2007-09-11', 'Türkenschanzpark', 'outdoor event', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Brewery Tour', '2008-06-30', 'Ottakringer Brauerei', 'guided tour', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Autumn Festival', '2009-10-05', 'Rochusmarkt', 'cultural festival', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Crafts Workshop', '2010-07-20', 'Margaretenplatz', 'workshop', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau Designer Expo', '2011-02-11', 'Neubaugasse', 'design expo', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Local History Tour', '2012-05-08', 'Technisches Museum', 'guided walk', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Vienna Classical Music Festival', '2013-11-15', 'Musikverein', 'classical music', 1);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Art and Wine Night', '2014-08-09', 'Karmelitermarkt', 'wine and art', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Theatre Marathon', '2015-09-27', 'Theater in der Josefstadt', 'theatre festival', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Science Day', '2016-03-21', 'Old AKH', 'science festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Dance Festival', '2017-04-14', 'Am Hauptbahnhof', 'dance festival', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Art Fair', '2018-10-20', 'Simmeringer Hauptstraße', 'art fair', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Food Tasting Event', '2019-07-11', 'Meidlinger Markt', 'food festival', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Photography Exhibition', '2020-06-05', 'Am Spitz', 'photography exhibition', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Währing Garden Exhibition', '2021-05-18', 'Türkenschanzpark', 'garden show', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Wine Festival', '2022-09-15', 'Hernalser Hauptstraße', 'wine festival', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim Craft Fair', '2023-12-01', 'Reindorfgasse', 'craft fair', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Winter Lights', '2024-01-24', 'Handelskai', 'light festival', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Photography Workshop', '2002-05-10', 'Linzer Straße', 'photography workshop', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Ottakring Summer Fest', '2004-07-25', 'Ottakringer Brauerei', 'summer festival', 16);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Meidling Local Crafts Fair', '2005-11-18', 'Meidlinger Hauptstraße', 'crafts fair', 12);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donaustadt Environmental Workshop', '2007-04-15', 'Lobau', 'environmental workshop', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Spring Arts Fair', '2008-05-22', 'Hernalser Hauptstraße', 'arts fair', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Book Night', '2009-10-30', 'Währinger Straße', 'book night', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Rudolfsheim-Fünfhaus Music Night', '2011-03-13', 'Reindorfgasse', 'music night', 15);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hietzing Cultural Evening', '2013-09-07', 'Hietzinger Hauptstraße', 'cultural evening', 13);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Theater Night', '2016-06-09', 'Prater Hauptallee', 'theater night', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Wieden Artisans Market', '2018-08-04', 'Karlsplatz', 'artisans market', 4);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Cultural Festival', '2020-07-19', 'Am Spitz', 'cultural festival', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Autumn Fair', '2023-10-12', 'Brigittenauer Lände', 'autumn fair', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Spring Gala', '2024-03-25', 'Rennweg', 'spring gala', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Margareten Summer Film Festival', '2021-06-16', 'Margaretenplatz', 'film festival', 5);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Josefstadt Jazz Festival', '2022-11-11', 'Josefstädter Straße', 'jazz festival', 8);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Favoriten Dance Workshop', '2023-08-14', 'Quellenstraße', 'dance workshop', 10);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Simmering Autumn Crafts Fair', '2024-09-21', 'Simmeringer Hauptstraße', 'crafts fair', 11);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Währing Film Night', '2003-10-07', 'Gersthofer Straße', 'film night', 18);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Döbling Literary Evening', '2006-11-19', 'Heiligenstädter Straße', 'literary evening', 19);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Alsergrund Science Festival', '2019-05-22', 'Alser Straße', 'science festival', 9);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Donaustadt Water Sports Day', '2001-08-12', 'Alte Donau', 'water sports', 22);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Penzing Winter Arts Festival', '2002-12-15', 'Hütteldorfer Straße', 'arts festival', 14);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Neubau Summer Music Festival', '2018-07-08', 'Spittelberggasse', 'music festival', 7);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Hernals Winter Festival', '2017-02-18', 'Kalvarienberggasse', 'winter festival', 17);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Leopoldstadt Spring Arts Festival', '2020-04-25', 'Karmelitermarkt', 'arts festival', 2);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Floridsdorf Jazz Evening', '2019-09-30', 'Floridsdorfer Hauptstraße', 'jazz evening', 21);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Brigittenau Summer Cinema', '2021-07-09', 'Handelskai', 'summer cinema', 20);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Landstraße Autumn Music Festival', '2022-10-07', 'Landstraßer Hauptstraße', 'music festival', 3);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Classical Music Evening', '2001-09-14', 'Perchtoldsdorfer Straße', 'classical music', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Spring Flower Show', '2003-04-12', 'Breitenfurter Straße', 'flower show', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Autumn Wine Tasting', '2005-10-21', 'Liesinger Platz', 'wine tasting', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Summer Jazz Festival', '2007-07-18', 'Atzgersdorfer Platz', 'jazz festival', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Christmas Market', '2010-12-05', 'Rodauner Straße', 'christmas market', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Art and Craft Fair', '2012-11-08', 'Ketzergasse', 'craft fair', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Film Festival', '2015-06-19', 'Liesingbachstraße', 'film festival', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Photography Exhibition', '2017-08-22', 'Anton-Baumgartner-Straße', 'photography exhibition', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Historical Reenactment', '2019-05-16', 'Alt-Erlaa', 'historical reenactment', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Community Sports Day', '2021-03-30', 'Liesing Park', 'community sports', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Outdoor Theatre', '2022-09-14', 'Maurer Hauptplatz', 'outdoor theatre', 23);
insert into Event (Name, Date, Address, Type, DistrictNr) values ('Liesing Science and Nature Day', '2024-04-05', 'Riverside', 'science and nature day', 23);
